version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-cafeteria-api-rest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k9kihvmaco1q"
s3_prefix = "sam-cafeteria-api-rest"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
