AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-cafeteria

  Sample SAM Template for sam-cafeteria
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  FetchAllProducts:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest/
      Handler: app.FetchAllProducts
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        FetchAllProducts:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /FetchAllProducts
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable
  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cafeteria-sam-api
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  CreateProduct:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest/
      Handler: app.CreateProduct
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateProduct:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /CreateProduct
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable
  DeleteProduct:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest/
      Handler: app.DeleteProduct
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteProduct:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /DeleteProduct/{id}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable
  UpdateProduct:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rest/
      Handler: app.UpdateProduct
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UpdateProduct:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /UpdateProduct/{id}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductTable


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

